### ISSUE TITLE
Map isn't showing on the github.io page.

### ISSUE THREAD

**Issue by RabblerouserGT** [tetreum/nukemap#1]
As the title says, the map isn't showing. I'm aware this is a new fork and all, though.

- Adblockers are all disabled
- Most importantly, the console is spitting a few errors out, and I think the most likely one is a 403 Forbidden error Failed to load resource: the server responded with a status of 403 (Forbidden) from api.mapbox.com.

Would this work if I cloned this to local?

**Comment by tetreum** [comment]
It seems like Alex didn't like this repo so he blocked his mapbox key. I will try to change it and see if it goes back to normality

**Comment by tetreum** [comment]
fixed.
